name: Deploy to GitHub Pages

on:
  push:
    branches:
      - hugo
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby: [ '2.7' ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Clone contents from nyeong/hanassig
        uses: actions/checkout@v3
        with:
          repository: nyeong/hanassig
          path: content

      - run: cp -r content-prepared/* content/
      - run: mkdir -p assets/indices

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: ruby ./bin/update-link-format.rb
      
      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.18
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # deploying branch
          cname: annyeong.me
