name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone contents from nyeong/hanassig
        uses: actions/checkout@v3
        with:
          repository: nyeong/hanassig
          path: hanassig
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: master
          cname: annyeong.me
